-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_16\hdlcoderfftdit\HDLFFTDUT_pkg.vhd
-- Created: 2016-12-14 11:10:45
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE HDLFFTDUT_pkg IS
  TYPE vector_of_unsigned4 IS ARRAY (NATURAL RANGE <>) OF unsigned(3 DOWNTO 0);
  TYPE vector_of_unsigned3 IS ARRAY (NATURAL RANGE <>) OF unsigned(2 DOWNTO 0);
END HDLFFTDUT_pkg;

