-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_16\hdlcoderfftdit\TwiddleTable.vhd
-- Created: 2016-12-17 21:37:37
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TwiddleTable
-- Source Path: hdlcoderfftdit/HDLFFTDUT/HDL FFT
-- Hierarchy Level: 2
-- 
-- Instantiate a Twiddle Table Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TwiddleTable IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        twindex                           :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        twiddle_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        twiddle_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END TwiddleTable;


ARCHITECTURE rtl OF TwiddleTable IS

  -- Signals
  SIGNAL twindex_unsigned                 : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL twiddle_re_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddle_im_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddletable_re                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddletable_im                  : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  twindex_unsigned <= unsigned(twindex);

  -- Instantiate a Twiddle Table Component
--  Twiddle Table
  PROCESS(twindex_unsigned)
  BEGIN
    CASE twindex_unsigned IS
      WHEN "0001" => twiddletable_re <= "0111011001000010";
      WHEN "0010" => twiddletable_re <= "0101101010000010";
      WHEN "0011" => twiddletable_re <= "0011000011111100";
      WHEN "0100" => twiddletable_re <= "0000000000000000";
      WHEN "0101" => twiddletable_re <= "1100111100000100";
      WHEN "0110" => twiddletable_re <= "1010010101111110";
      WHEN "0111" => twiddletable_re <= "1000100110111110";
      WHEN OTHERS => twiddletable_re <= "1000100110111110";
    END CASE;
  END PROCESS;

  PROCESS(twindex_unsigned)
  BEGIN
    CASE twindex_unsigned IS
      WHEN "0001" => twiddletable_im <= "1100111100000100";
      WHEN "0010" => twiddletable_im <= "1010010101111110";
      WHEN "0011" => twiddletable_im <= "1000100110111110";
      WHEN "0100" => twiddletable_im <= "1000000000000000";
      WHEN "0101" => twiddletable_im <= "1000100110111110";
      WHEN "0110" => twiddletable_im <= "1010010101111110";
      WHEN "0111" => twiddletable_im <= "1100111100000100";
      WHEN OTHERS => twiddletable_im <= "1100111100000100";
    END CASE;
  END PROCESS;

  temp_process21_Delay_twiddle : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddle_re_tmp <= (OTHERS => '0');
      twiddle_im_tmp <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        twiddle_re_tmp <= twiddletable_re;
        twiddle_im_tmp <= twiddletable_im;
      END IF;
    END IF;
  END PROCESS temp_process21_Delay_twiddle;


  twiddle_re <= std_logic_vector(twiddle_re_tmp);

  twiddle_im <= std_logic_vector(twiddle_im_tmp);

END rtl;

