-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_64\hdlcoderfftdit\HDLFFTDUT.vhd
-- Created: 2016-12-14 11:11:15
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.0078125
-- Target subsystem base rate: 0.0078125
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.0078125
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- dvalid                        ce_out        0.0078125
-- ready                         ce_out        0.0078125
-- dout_re                       ce_out        0.0078125
-- dout_im                       ce_out        0.0078125
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: HDLFFTDUT
-- Source Path: hdlcoderfftdit/HDLFFTDUT
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY HDLFFTDUT IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        dIn_re                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dIn_im                            :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        start                             :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        dvalid                            :   OUT   std_logic;
        ready                             :   OUT   std_logic;
        dout_re                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
        dout_im                           :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En14
        );
END HDLFFTDUT;


ARCHITECTURE rtl OF HDLFFTDUT IS

  -- Component Declarations
  COMPONENT HDL_FFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          din_re                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          din_im                          :   IN    std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          start                           :   IN    std_logic;
          dout_re                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dout_im                         :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En14
          dvalid                          :   OUT   std_logic;
          ready                           :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : HDL_FFT
    USE ENTITY work.HDL_FFT(rtl);

  -- Signals
  SIGNAL HDL_FFT_out1_re                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL HDL_FFT_out1_im                  : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Ready_1                          : std_logic;

BEGIN
  u_HDL_FFT : HDL_FFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              din_re => dIn_re,  -- sfix16_En14
              din_im => dIn_im,  -- sfix16_En14
              start => start,
              dout_re => HDL_FFT_out1_re,  -- sfix16_En14
              dout_im => HDL_FFT_out1_im,  -- sfix16_En14
              dvalid => dvalid,
              ready => Ready_1
              );

  ce_out <= clk_enable;

  ready <= Ready_1;

  dout_re <= HDL_FFT_out1_re;

  dout_im <= HDL_FFT_out1_im;

END rtl;

