-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_64\hdlcoderfftdit\HDLFFTDUT_pkg.vhd
-- Created: 2016-12-14 11:11:15
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE HDLFFTDUT_pkg IS
  TYPE vector_of_unsigned6 IS ARRAY (NATURAL RANGE <>) OF unsigned(5 DOWNTO 0);
  TYPE vector_of_unsigned5 IS ARRAY (NATURAL RANGE <>) OF unsigned(4 DOWNTO 0);
END HDLFFTDUT_pkg;

