-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_64\hdlcoderfftdit\TwiddleTable.vhd
-- Created: 2016-12-14 11:11:15
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TwiddleTable
-- Source Path: hdlcoderfftdit/HDLFFTDUT/HDL FFT
-- Hierarchy Level: 2
-- 
-- Instantiate a Twiddle Table Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TwiddleTable IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        twindex                           :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        twiddle_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        twiddle_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END TwiddleTable;


ARCHITECTURE rtl OF TwiddleTable IS

  -- Signals
  SIGNAL twindex_unsigned                 : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL twiddle_re_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddle_im_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddletable_re                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddletable_im                  : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  twindex_unsigned <= unsigned(twindex);

  -- Instantiate a Twiddle Table Component
--  Twiddle Table
  PROCESS(twindex_unsigned)
  BEGIN
    CASE twindex_unsigned IS
      WHEN "000001" => twiddletable_re <= "0111111101100010";
      WHEN "000010" => twiddletable_re <= "0111110110001010";
      WHEN "000011" => twiddletable_re <= "0111101001111101";
      WHEN "000100" => twiddletable_re <= "0111011001000010";
      WHEN "000101" => twiddletable_re <= "0111000011100011";
      WHEN "000110" => twiddletable_re <= "0110101001101110";
      WHEN "000111" => twiddletable_re <= "0110001011110010";
      WHEN "001000" => twiddletable_re <= "0101101010000010";
      WHEN "001001" => twiddletable_re <= "0101000100110100";
      WHEN "001010" => twiddletable_re <= "0100011100011101";
      WHEN "001011" => twiddletable_re <= "0011110001010111";
      WHEN "001100" => twiddletable_re <= "0011000011111100";
      WHEN "001101" => twiddletable_re <= "0010010100101000";
      WHEN "001110" => twiddletable_re <= "0001100011111001";
      WHEN "001111" => twiddletable_re <= "0000110010001100";
      WHEN "010000" => twiddletable_re <= "0000000000000000";
      WHEN "010001" => twiddletable_re <= "1111001101110100";
      WHEN "010010" => twiddletable_re <= "1110011100000111";
      WHEN "010011" => twiddletable_re <= "1101101011011000";
      WHEN "010100" => twiddletable_re <= "1100111100000100";
      WHEN "010101" => twiddletable_re <= "1100001110101001";
      WHEN "010110" => twiddletable_re <= "1011100011100011";
      WHEN "010111" => twiddletable_re <= "1010111011001100";
      WHEN "011000" => twiddletable_re <= "1010010101111110";
      WHEN "011001" => twiddletable_re <= "1001110100001110";
      WHEN "011010" => twiddletable_re <= "1001010110010010";
      WHEN "011011" => twiddletable_re <= "1000111100011101";
      WHEN "011100" => twiddletable_re <= "1000100110111110";
      WHEN "011101" => twiddletable_re <= "1000010110000011";
      WHEN "011110" => twiddletable_re <= "1000001001110110";
      WHEN "011111" => twiddletable_re <= "1000000010011110";
      WHEN OTHERS => twiddletable_re <= "1000000010011110";
    END CASE;
  END PROCESS;

  PROCESS(twindex_unsigned)
  BEGIN
    CASE twindex_unsigned IS
      WHEN "000001" => twiddletable_im <= "1111001101110100";
      WHEN "000010" => twiddletable_im <= "1110011100000111";
      WHEN "000011" => twiddletable_im <= "1101101011011000";
      WHEN "000100" => twiddletable_im <= "1100111100000100";
      WHEN "000101" => twiddletable_im <= "1100001110101001";
      WHEN "000110" => twiddletable_im <= "1011100011100011";
      WHEN "000111" => twiddletable_im <= "1010111011001100";
      WHEN "001000" => twiddletable_im <= "1010010101111110";
      WHEN "001001" => twiddletable_im <= "1001110100001110";
      WHEN "001010" => twiddletable_im <= "1001010110010010";
      WHEN "001011" => twiddletable_im <= "1000111100011101";
      WHEN "001100" => twiddletable_im <= "1000100110111110";
      WHEN "001101" => twiddletable_im <= "1000010110000011";
      WHEN "001110" => twiddletable_im <= "1000001001110110";
      WHEN "001111" => twiddletable_im <= "1000000010011110";
      WHEN "010000" => twiddletable_im <= "1000000000000000";
      WHEN "010001" => twiddletable_im <= "1000000010011110";
      WHEN "010010" => twiddletable_im <= "1000001001110110";
      WHEN "010011" => twiddletable_im <= "1000010110000011";
      WHEN "010100" => twiddletable_im <= "1000100110111110";
      WHEN "010101" => twiddletable_im <= "1000111100011101";
      WHEN "010110" => twiddletable_im <= "1001010110010010";
      WHEN "010111" => twiddletable_im <= "1001110100001110";
      WHEN "011000" => twiddletable_im <= "1010010101111110";
      WHEN "011001" => twiddletable_im <= "1010111011001100";
      WHEN "011010" => twiddletable_im <= "1011100011100011";
      WHEN "011011" => twiddletable_im <= "1100001110101001";
      WHEN "011100" => twiddletable_im <= "1100111100000100";
      WHEN "011101" => twiddletable_im <= "1101101011011000";
      WHEN "011110" => twiddletable_im <= "1110011100000111";
      WHEN "011111" => twiddletable_im <= "1111001101110100";
      WHEN OTHERS => twiddletable_im <= "1111001101110100";
    END CASE;
  END PROCESS;

  temp_process21_Delay_twiddle : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddle_re_tmp <= (OTHERS => '0');
      twiddle_im_tmp <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        twiddle_re_tmp <= twiddletable_re;
        twiddle_im_tmp <= twiddletable_im;
      END IF;
    END IF;
  END PROCESS temp_process21_Delay_twiddle;


  twiddle_re <= std_logic_vector(twiddle_re_tmp);

  twiddle_im <= std_logic_vector(twiddle_im_tmp);

END rtl;

