-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_256\hdlcoderfftdit\HDLFFTDUT_pkg.vhd
-- Created: 2016-12-19 13:39:19
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE HDLFFTDUT_pkg IS
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE vector_of_unsigned7 IS ARRAY (NATURAL RANGE <>) OF unsigned(6 DOWNTO 0);
END HDLFFTDUT_pkg;

