-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_256\hdlcoderfftdit\TwiddleTable.vhd
-- Created: 2016-12-19 13:39:19
-- 
-- Generated by MATLAB 9.1 and HDL Coder 3.9
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TwiddleTable
-- Source Path: hdlcoderfftdit/HDLFFTDUT/HDL FFT
-- Hierarchy Level: 2
-- 
-- Instantiate a Twiddle Table Component
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY TwiddleTable IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        twindex                           :   IN    std_logic_vector(7 DOWNTO 0);  -- ufix8
        twiddle_re                        :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En15
        twiddle_im                        :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En15
        );
END TwiddleTable;


ARCHITECTURE rtl OF TwiddleTable IS

  -- Signals
  SIGNAL twindex_unsigned                 : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL twiddle_re_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddle_im_tmp                   : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddletable_re                  : signed(15 DOWNTO 0);  -- sfix16_En15
  SIGNAL twiddletable_im                  : signed(15 DOWNTO 0);  -- sfix16_En15

BEGIN
  twindex_unsigned <= unsigned(twindex);

  -- Instantiate a Twiddle Table Component
--  Twiddle Table
  PROCESS(twindex_unsigned)
  BEGIN
    CASE twindex_unsigned IS
      WHEN "00000001" => twiddletable_re <= "0111111111110110";
      WHEN "00000010" => twiddletable_re <= "0111111111011001";
      WHEN "00000011" => twiddletable_re <= "0111111110100111";
      WHEN "00000100" => twiddletable_re <= "0111111101100010";
      WHEN "00000101" => twiddletable_re <= "0111111100001010";
      WHEN "00000110" => twiddletable_re <= "0111111010011101";
      WHEN "00000111" => twiddletable_re <= "0111111000011110";
      WHEN "00001000" => twiddletable_re <= "0111110110001010";
      WHEN "00001001" => twiddletable_re <= "0111110011100100";
      WHEN "00001010" => twiddletable_re <= "0111110000101010";
      WHEN "00001011" => twiddletable_re <= "0111101101011101";
      WHEN "00001100" => twiddletable_re <= "0111101001111101";
      WHEN "00001101" => twiddletable_re <= "0111100110001010";
      WHEN "00001110" => twiddletable_re <= "0111100010000101";
      WHEN "00001111" => twiddletable_re <= "0111011101101100";
      WHEN "00010000" => twiddletable_re <= "0111011001000010";
      WHEN "00010001" => twiddletable_re <= "0111010100000101";
      WHEN "00010010" => twiddletable_re <= "0111001110110110";
      WHEN "00010011" => twiddletable_re <= "0111001001010101";
      WHEN "00010100" => twiddletable_re <= "0111000011100011";
      WHEN "00010101" => twiddletable_re <= "0110111101011111";
      WHEN "00010110" => twiddletable_re <= "0110110111001010";
      WHEN "00010111" => twiddletable_re <= "0110110000100100";
      WHEN "00011000" => twiddletable_re <= "0110101001101110";
      WHEN "00011001" => twiddletable_re <= "0110100010100111";
      WHEN "00011010" => twiddletable_re <= "0110011011010000";
      WHEN "00011011" => twiddletable_re <= "0110010011101001";
      WHEN "00011100" => twiddletable_re <= "0110001011110010";
      WHEN "00011101" => twiddletable_re <= "0110000011101100";
      WHEN "00011110" => twiddletable_re <= "0101111011010111";
      WHEN "00011111" => twiddletable_re <= "0101110010110100";
      WHEN "00100000" => twiddletable_re <= "0101101010000010";
      WHEN "00100001" => twiddletable_re <= "0101100001000011";
      WHEN "00100010" => twiddletable_re <= "0101010111110110";
      WHEN "00100011" => twiddletable_re <= "0101001110011011";
      WHEN "00100100" => twiddletable_re <= "0101000100110100";
      WHEN "00100101" => twiddletable_re <= "0100111011000000";
      WHEN "00100110" => twiddletable_re <= "0100110001000000";
      WHEN "00100111" => twiddletable_re <= "0100100110110100";
      WHEN "00101000" => twiddletable_re <= "0100011100011101";
      WHEN "00101001" => twiddletable_re <= "0100010001111011";
      WHEN "00101010" => twiddletable_re <= "0100000111001110";
      WHEN "00101011" => twiddletable_re <= "0011111100010111";
      WHEN "00101100" => twiddletable_re <= "0011110001010111";
      WHEN "00101101" => twiddletable_re <= "0011100110001101";
      WHEN "00101110" => twiddletable_re <= "0011011010111010";
      WHEN "00101111" => twiddletable_re <= "0011001111011111";
      WHEN "00110000" => twiddletable_re <= "0011000011111100";
      WHEN "00110001" => twiddletable_re <= "0010111000010001";
      WHEN "00110010" => twiddletable_re <= "0010101100011111";
      WHEN "00110011" => twiddletable_re <= "0010100000100111";
      WHEN "00110100" => twiddletable_re <= "0010010100101000";
      WHEN "00110101" => twiddletable_re <= "0010001000100100";
      WHEN "00110110" => twiddletable_re <= "0001111100011010";
      WHEN "00110111" => twiddletable_re <= "0001110000001100";
      WHEN "00111000" => twiddletable_re <= "0001100011111001";
      WHEN "00111001" => twiddletable_re <= "0001010111100010";
      WHEN "00111010" => twiddletable_re <= "0001001011001000";
      WHEN "00111011" => twiddletable_re <= "0000111110101011";
      WHEN "00111100" => twiddletable_re <= "0000110010001100";
      WHEN "00111101" => twiddletable_re <= "0000100101101011";
      WHEN "00111110" => twiddletable_re <= "0000011001001000";
      WHEN "00111111" => twiddletable_re <= "0000001100100100";
      WHEN "01000000" => twiddletable_re <= "0000000000000000";
      WHEN "01000001" => twiddletable_re <= "1111110011011100";
      WHEN "01000010" => twiddletable_re <= "1111100110111000";
      WHEN "01000011" => twiddletable_re <= "1111011010010101";
      WHEN "01000100" => twiddletable_re <= "1111001101110100";
      WHEN "01000101" => twiddletable_re <= "1111000001010101";
      WHEN "01000110" => twiddletable_re <= "1110110100111000";
      WHEN "01000111" => twiddletable_re <= "1110101000011110";
      WHEN "01001000" => twiddletable_re <= "1110011100000111";
      WHEN "01001001" => twiddletable_re <= "1110001111110100";
      WHEN "01001010" => twiddletable_re <= "1110000011100110";
      WHEN "01001011" => twiddletable_re <= "1101110111011100";
      WHEN "01001100" => twiddletable_re <= "1101101011011000";
      WHEN "01001101" => twiddletable_re <= "1101011111011001";
      WHEN "01001110" => twiddletable_re <= "1101010011100001";
      WHEN "01001111" => twiddletable_re <= "1101000111101111";
      WHEN "01010000" => twiddletable_re <= "1100111100000100";
      WHEN "01010001" => twiddletable_re <= "1100110000100001";
      WHEN "01010010" => twiddletable_re <= "1100100101000110";
      WHEN "01010011" => twiddletable_re <= "1100011001110011";
      WHEN "01010100" => twiddletable_re <= "1100001110101001";
      WHEN "01010101" => twiddletable_re <= "1100000011101001";
      WHEN "01010110" => twiddletable_re <= "1011111000110010";
      WHEN "01010111" => twiddletable_re <= "1011101110000101";
      WHEN "01011000" => twiddletable_re <= "1011100011100011";
      WHEN "01011001" => twiddletable_re <= "1011011001001100";
      WHEN "01011010" => twiddletable_re <= "1011001111000000";
      WHEN "01011011" => twiddletable_re <= "1011000101000000";
      WHEN "01011100" => twiddletable_re <= "1010111011001100";
      WHEN "01011101" => twiddletable_re <= "1010110001100101";
      WHEN "01011110" => twiddletable_re <= "1010101000001010";
      WHEN "01011111" => twiddletable_re <= "1010011110111101";
      WHEN "01100000" => twiddletable_re <= "1010010101111110";
      WHEN "01100001" => twiddletable_re <= "1010001101001100";
      WHEN "01100010" => twiddletable_re <= "1010000100101001";
      WHEN "01100011" => twiddletable_re <= "1001111100010100";
      WHEN "01100100" => twiddletable_re <= "1001110100001110";
      WHEN "01100101" => twiddletable_re <= "1001101100010111";
      WHEN "01100110" => twiddletable_re <= "1001100100110000";
      WHEN "01100111" => twiddletable_re <= "1001011101011001";
      WHEN "01101000" => twiddletable_re <= "1001010110010010";
      WHEN "01101001" => twiddletable_re <= "1001001111011100";
      WHEN "01101010" => twiddletable_re <= "1001001000110110";
      WHEN "01101011" => twiddletable_re <= "1001000010100001";
      WHEN "01101100" => twiddletable_re <= "1000111100011101";
      WHEN "01101101" => twiddletable_re <= "1000110110101011";
      WHEN "01101110" => twiddletable_re <= "1000110001001010";
      WHEN "01101111" => twiddletable_re <= "1000101011111011";
      WHEN "01110000" => twiddletable_re <= "1000100110111110";
      WHEN "01110001" => twiddletable_re <= "1000100010010100";
      WHEN "01110010" => twiddletable_re <= "1000011101111011";
      WHEN "01110011" => twiddletable_re <= "1000011001110110";
      WHEN "01110100" => twiddletable_re <= "1000010110000011";
      WHEN "01110101" => twiddletable_re <= "1000010010100011";
      WHEN "01110110" => twiddletable_re <= "1000001111010110";
      WHEN "01110111" => twiddletable_re <= "1000001100011100";
      WHEN "01111000" => twiddletable_re <= "1000001001110110";
      WHEN "01111001" => twiddletable_re <= "1000000111100010";
      WHEN "01111010" => twiddletable_re <= "1000000101100011";
      WHEN "01111011" => twiddletable_re <= "1000000011110110";
      WHEN "01111100" => twiddletable_re <= "1000000010011110";
      WHEN "01111101" => twiddletable_re <= "1000000001011001";
      WHEN "01111110" => twiddletable_re <= "1000000000100111";
      WHEN "01111111" => twiddletable_re <= "1000000000001010";
      WHEN OTHERS => twiddletable_re <= "1000000000001010";
    END CASE;
  END PROCESS;

  PROCESS(twindex_unsigned)
  BEGIN
    CASE twindex_unsigned IS
      WHEN "00000001" => twiddletable_im <= "1111110011011100";
      WHEN "00000010" => twiddletable_im <= "1111100110111000";
      WHEN "00000011" => twiddletable_im <= "1111011010010101";
      WHEN "00000100" => twiddletable_im <= "1111001101110100";
      WHEN "00000101" => twiddletable_im <= "1111000001010101";
      WHEN "00000110" => twiddletable_im <= "1110110100111000";
      WHEN "00000111" => twiddletable_im <= "1110101000011110";
      WHEN "00001000" => twiddletable_im <= "1110011100000111";
      WHEN "00001001" => twiddletable_im <= "1110001111110100";
      WHEN "00001010" => twiddletable_im <= "1110000011100110";
      WHEN "00001011" => twiddletable_im <= "1101110111011100";
      WHEN "00001100" => twiddletable_im <= "1101101011011000";
      WHEN "00001101" => twiddletable_im <= "1101011111011001";
      WHEN "00001110" => twiddletable_im <= "1101010011100001";
      WHEN "00001111" => twiddletable_im <= "1101000111101111";
      WHEN "00010000" => twiddletable_im <= "1100111100000100";
      WHEN "00010001" => twiddletable_im <= "1100110000100001";
      WHEN "00010010" => twiddletable_im <= "1100100101000110";
      WHEN "00010011" => twiddletable_im <= "1100011001110011";
      WHEN "00010100" => twiddletable_im <= "1100001110101001";
      WHEN "00010101" => twiddletable_im <= "1100000011101001";
      WHEN "00010110" => twiddletable_im <= "1011111000110010";
      WHEN "00010111" => twiddletable_im <= "1011101110000101";
      WHEN "00011000" => twiddletable_im <= "1011100011100011";
      WHEN "00011001" => twiddletable_im <= "1011011001001100";
      WHEN "00011010" => twiddletable_im <= "1011001111000000";
      WHEN "00011011" => twiddletable_im <= "1011000101000000";
      WHEN "00011100" => twiddletable_im <= "1010111011001100";
      WHEN "00011101" => twiddletable_im <= "1010110001100101";
      WHEN "00011110" => twiddletable_im <= "1010101000001010";
      WHEN "00011111" => twiddletable_im <= "1010011110111101";
      WHEN "00100000" => twiddletable_im <= "1010010101111110";
      WHEN "00100001" => twiddletable_im <= "1010001101001100";
      WHEN "00100010" => twiddletable_im <= "1010000100101001";
      WHEN "00100011" => twiddletable_im <= "1001111100010100";
      WHEN "00100100" => twiddletable_im <= "1001110100001110";
      WHEN "00100101" => twiddletable_im <= "1001101100010111";
      WHEN "00100110" => twiddletable_im <= "1001100100110000";
      WHEN "00100111" => twiddletable_im <= "1001011101011001";
      WHEN "00101000" => twiddletable_im <= "1001010110010010";
      WHEN "00101001" => twiddletable_im <= "1001001111011100";
      WHEN "00101010" => twiddletable_im <= "1001001000110110";
      WHEN "00101011" => twiddletable_im <= "1001000010100001";
      WHEN "00101100" => twiddletable_im <= "1000111100011101";
      WHEN "00101101" => twiddletable_im <= "1000110110101011";
      WHEN "00101110" => twiddletable_im <= "1000110001001010";
      WHEN "00101111" => twiddletable_im <= "1000101011111011";
      WHEN "00110000" => twiddletable_im <= "1000100110111110";
      WHEN "00110001" => twiddletable_im <= "1000100010010100";
      WHEN "00110010" => twiddletable_im <= "1000011101111011";
      WHEN "00110011" => twiddletable_im <= "1000011001110110";
      WHEN "00110100" => twiddletable_im <= "1000010110000011";
      WHEN "00110101" => twiddletable_im <= "1000010010100011";
      WHEN "00110110" => twiddletable_im <= "1000001111010110";
      WHEN "00110111" => twiddletable_im <= "1000001100011100";
      WHEN "00111000" => twiddletable_im <= "1000001001110110";
      WHEN "00111001" => twiddletable_im <= "1000000111100010";
      WHEN "00111010" => twiddletable_im <= "1000000101100011";
      WHEN "00111011" => twiddletable_im <= "1000000011110110";
      WHEN "00111100" => twiddletable_im <= "1000000010011110";
      WHEN "00111101" => twiddletable_im <= "1000000001011001";
      WHEN "00111110" => twiddletable_im <= "1000000000100111";
      WHEN "00111111" => twiddletable_im <= "1000000000001010";
      WHEN "01000000" => twiddletable_im <= "1000000000000000";
      WHEN "01000001" => twiddletable_im <= "1000000000001010";
      WHEN "01000010" => twiddletable_im <= "1000000000100111";
      WHEN "01000011" => twiddletable_im <= "1000000001011001";
      WHEN "01000100" => twiddletable_im <= "1000000010011110";
      WHEN "01000101" => twiddletable_im <= "1000000011110110";
      WHEN "01000110" => twiddletable_im <= "1000000101100011";
      WHEN "01000111" => twiddletable_im <= "1000000111100010";
      WHEN "01001000" => twiddletable_im <= "1000001001110110";
      WHEN "01001001" => twiddletable_im <= "1000001100011100";
      WHEN "01001010" => twiddletable_im <= "1000001111010110";
      WHEN "01001011" => twiddletable_im <= "1000010010100011";
      WHEN "01001100" => twiddletable_im <= "1000010110000011";
      WHEN "01001101" => twiddletable_im <= "1000011001110110";
      WHEN "01001110" => twiddletable_im <= "1000011101111011";
      WHEN "01001111" => twiddletable_im <= "1000100010010100";
      WHEN "01010000" => twiddletable_im <= "1000100110111110";
      WHEN "01010001" => twiddletable_im <= "1000101011111011";
      WHEN "01010010" => twiddletable_im <= "1000110001001010";
      WHEN "01010011" => twiddletable_im <= "1000110110101011";
      WHEN "01010100" => twiddletable_im <= "1000111100011101";
      WHEN "01010101" => twiddletable_im <= "1001000010100001";
      WHEN "01010110" => twiddletable_im <= "1001001000110110";
      WHEN "01010111" => twiddletable_im <= "1001001111011100";
      WHEN "01011000" => twiddletable_im <= "1001010110010010";
      WHEN "01011001" => twiddletable_im <= "1001011101011001";
      WHEN "01011010" => twiddletable_im <= "1001100100110000";
      WHEN "01011011" => twiddletable_im <= "1001101100010111";
      WHEN "01011100" => twiddletable_im <= "1001110100001110";
      WHEN "01011101" => twiddletable_im <= "1001111100010100";
      WHEN "01011110" => twiddletable_im <= "1010000100101001";
      WHEN "01011111" => twiddletable_im <= "1010001101001100";
      WHEN "01100000" => twiddletable_im <= "1010010101111110";
      WHEN "01100001" => twiddletable_im <= "1010011110111101";
      WHEN "01100010" => twiddletable_im <= "1010101000001010";
      WHEN "01100011" => twiddletable_im <= "1010110001100101";
      WHEN "01100100" => twiddletable_im <= "1010111011001100";
      WHEN "01100101" => twiddletable_im <= "1011000101000000";
      WHEN "01100110" => twiddletable_im <= "1011001111000000";
      WHEN "01100111" => twiddletable_im <= "1011011001001100";
      WHEN "01101000" => twiddletable_im <= "1011100011100011";
      WHEN "01101001" => twiddletable_im <= "1011101110000101";
      WHEN "01101010" => twiddletable_im <= "1011111000110010";
      WHEN "01101011" => twiddletable_im <= "1100000011101001";
      WHEN "01101100" => twiddletable_im <= "1100001110101001";
      WHEN "01101101" => twiddletable_im <= "1100011001110011";
      WHEN "01101110" => twiddletable_im <= "1100100101000110";
      WHEN "01101111" => twiddletable_im <= "1100110000100001";
      WHEN "01110000" => twiddletable_im <= "1100111100000100";
      WHEN "01110001" => twiddletable_im <= "1101000111101111";
      WHEN "01110010" => twiddletable_im <= "1101010011100001";
      WHEN "01110011" => twiddletable_im <= "1101011111011001";
      WHEN "01110100" => twiddletable_im <= "1101101011011000";
      WHEN "01110101" => twiddletable_im <= "1101110111011100";
      WHEN "01110110" => twiddletable_im <= "1110000011100110";
      WHEN "01110111" => twiddletable_im <= "1110001111110100";
      WHEN "01111000" => twiddletable_im <= "1110011100000111";
      WHEN "01111001" => twiddletable_im <= "1110101000011110";
      WHEN "01111010" => twiddletable_im <= "1110110100111000";
      WHEN "01111011" => twiddletable_im <= "1111000001010101";
      WHEN "01111100" => twiddletable_im <= "1111001101110100";
      WHEN "01111101" => twiddletable_im <= "1111011010010101";
      WHEN "01111110" => twiddletable_im <= "1111100110111000";
      WHEN "01111111" => twiddletable_im <= "1111110011011100";
      WHEN OTHERS => twiddletable_im <= "1111110011011100";
    END CASE;
  END PROCESS;

  temp_process21_Delay_twiddle : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddle_re_tmp <= (OTHERS => '0');
      twiddle_im_tmp <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF enb = '1' THEN
        twiddle_re_tmp <= twiddletable_re;
        twiddle_im_tmp <= twiddletable_im;
      END IF;
    END IF;
  END PROCESS temp_process21_Delay_twiddle;


  twiddle_re <= std_logic_vector(twiddle_re_tmp);

  twiddle_im <= std_logic_vector(twiddle_im_tmp);

END rtl;

